export const PREGNERATED_TABLES: {
    [key: string]: { poolSize: number; table: { [roll: number]: string } };
  } = {
    "inspiring-d4": {
    poolSize: 4,
    table: {
      1: "An inspiring mentor appears",
      2: "A mysterious benefactor offers aid",
      3: "A fabled hero shares a secret",
      4: "A wise sage foretells a grand adventure",
    },
    },
    "goblin-d6": {
      poolSize: 6,
      table: {
        1: "A lone goblin",
        2: "Two goblins",
        3: "A goblin archer",
        4: "A group of goblins",
        5: "A goblin shaman",
        6: "A goblin chief",
      },
    },
    "epic-d8": {
      poolSize: 8,
      table: {
        1: "A band of heroic knights",
        2: "An undead legion",
        3: "A horde of orcs",
        4: "A cunning bandit crew",
        5: "A mythical beast",
        6: "A council of wizards",
        7: "A covert spy network",
        8: "A fearsome dragon",
      },
    },
    "mythic-d10": {
      poolSize: 10,
      table: {
        1: "A cursed relic",
        2: "A divine vision",
        3: "A legendary sword",
        4: "A vengeful spirit",
        5: "A hidden treasure",
        6: "A prophecy revealed",
        7: "An ancient ruin",
        8: "A fabled hero",
        9: "A mysterious portal",
        10: "A secret passage",
      },
    },
    "grand-d20": {
      poolSize: 20,
      table: {
        1: "A royal decree",
        2: "A hidden kingdom",
        3: "An enigmatic wizard",
        4: "A cursed village",
        5: "A perilous quest",
        6: "A fabled treasure",
        7: "A notorious bandit leader",
        8: "A magical anomaly",
        9: "A covert spy network",
        10: "A powerful artifact",
        11: "A dangerous cult",
        12: "A legendary beast",
        13: "A secret rebellion",
        14: "A prophetic vision",
        15: "A lost civilization",
        16: "A mighty warlord",
        17: "An ancient curse",
        18: "A mystical ritual",
        19: "A forgotten god",
        20: "A world-altering event",
      },
    },
        "colossal-d100": {
          poolSize: 100,
          table: {
            1: "A humble beginning",
            2: "A sudden storm disrupts travel",
            3: "A cryptic letter from an unknown sender",
            4: "A hidden message in an ancient text",
            5: "A strange dream with a forgotten prophecy",
            6: "A lost heirloom found in an unlikely place",
            7: "A secret map to an uncharted island",
            8: "A powerful enemy seeks revenge",
            9: "A forgotten legend resurfaces",
            10: "A dangerous journey through cursed lands",
            11: "A magical artifact with untapped potential",
            12: "A hidden passage in the castle walls",
            13: "A mystical forest filled with whispers",
            14: "A haunted mansion with restless spirits",
            15: "A treacherous mountain climb",
            16: "A forbidden spell that warps reality",
            17: "A legendary hero thought to be dead",
            18: "A cursed item bringing misfortune",
            19: "A hidden treasure in an underwater ruin",
            20: "A powerful ally offering an unexpected deal",
            21: "A secret society manipulating events",
            22: "A lost city emerging from the sands",
            23: "A mythical creature guarding an ancient relic",
            24: "A deadly trap waiting to be triggered",
            25: "A hidden cave with glowing crystals",
            26: "A powerful spell locked away for centuries",
            27: "A secret weapon with world-altering power",
            28: "A mysterious stranger offering guidance",
            29: "A hidden agenda among trusted allies",
            30: "A massive war brewing between kingdoms",
            31: "A ghost ship appearing on moonlit nights",
            32: "A cursed village where time stands still",
            33: "A dangerous foe hunting the party",
            34: "A hidden power awakening inside someone",
            35: "A mysterious artifact draining nearby magic",
            36: "A powerful potion with unknown side effects",
            37: "A secret hideout for rebel forces",
            38: "A dungeon untouched for a thousand years",
            39: "A portal opening to an unknown realm",
            40: "A dangerous quest forced upon the heroes",
            41: "A secret passage leading beneath the city",
            42: "A kingdom at war with an unseen enemy",
            43: "A rogue star falling from the sky",
            44: "A powerful enemy with mind control abilities",
            45: "A forgotten deity seeking worshipers",
            46: "A forbidden ritual taking place in secret",
            47: "A shadowy organization pulling the strings",
            48: "A hidden vault filled with lost knowledge",
            49: "A secret ritual requiring a willing sacrifice",
            50: "A dangerous journey across a monster-infested wasteland",
            51: "A hidden cave containing a prophecy",
            52: "A powerful artifact warping reality around it",
            53: "A secret society pulling the world’s strings",
            54: "A monstrous entity awakening after centuries of slumber",
            55: "A hidden power buried deep underground",
            56: "A secret mission to recover a stolen relic",
            57: "A magical storm that erases memories",
            58: "A dungeon filled with shifting walls",
            59: "A noble family hiding a dark secret",
            60: "A mysterious ancient machine coming to life",
            61: "A forbidden library guarded by arcane wards",
            62: "A dangerous journey into the Feywild",
            63: "A hidden passage into a long-forgotten kingdom",
            64: "A group of celestial beings watching the party",
            65: "A secret hideout of a powerful assassin’s guild",
            66: "A dangerous quest to retrieve a stolen soul",
            67: "A kingdom ruled by an immortal sorcerer",
            68: "A legendary beast awakening from its slumber",
            69: "A long-lost airship crashing into the sea",
            70: "A cursed artifact turning those who touch it into stone",
            71: "A secret underground city thriving in the dark",
            72: "A dangerous criminal offering unexpected aid",
            73: "A divine entity speaking directly to the party",
            74: "A war between dragons threatening the world",
            75: "A powerful artifact choosing a new wielder",
            76: "A secretive vampire lord manipulating politics",
            77: "A portal that swaps places between realities",
            78: "A demonic invasion breaking through the veil",
            79: "A hidden power sleeping inside an ancient blade",
            80: "A divine trial testing the party’s worthiness",
            81: "A lost civilization resurfacing from the depths",
            82: "A legendary hero returning after centuries of exile",
            83: "A mystical order of monks safeguarding a universal truth",
            84: "A dungeon where time flows unpredictably",
            85: "A secret message hidden in the stars",
            86: "A powerful ally hiding their true nature",
            87: "A royal heir vanishing under mysterious circumstances",
            88: "A sentient construct gaining independence",
            89: "A legendary warlord returning from the dead",
            90: "A cursed sea voyage filled with strange creatures",
            91: "A massive tournament where champions battle for godhood",
            92: "A secret war between planar factions",
            93: "A powerful deity offering a dangerous bargain",
            94: "A great city sinking into the abyss",
            95: "A hidden prophecy foretelling the party’s fate",
            96: "A great machine controlling fate itself",
            97: "A magical rift tearing through reality",
            98: "A god awakening from imprisonment",
            99: "A cataclysmic event shifting the world’s balance",
            100: "A mythic finale where the party decides the fate of the world",
          },
        },
      };